language: java
jdk:
  - openjdk14
addons:
  apt:
    packages:
      - fakeroot
      - rpm
cache:
  directories:
    - $HOME/.m2
before_install:
  - echo "MAVEN_OPTS='-Xmx3072m -XX:MaxPermSize=512m'" > ~/.mavenrc
