package de.erdesignerng;

/**
 * Automatically generated by XMLResourceBundleTask. DO NOT ALTER !
 */
public interface ERDesignerBundle {

  String BUNDLE_NAME = "de/erdesignerng/ERDesignerBundle";

  /** . */
  String TITLE = "TITLE";
  /** File. */
  String FILE = "FILE";
  /** Recently used files. */
  String RECENTLYUSEDFILES = "RECENTLYUSEDFILES";
  /** New model. */
  String NEWMODEL = "NEWMODEL";
  /** Save model.... */
  String SAVEMODEL = "SAVEMODEL";
  /** Save model to repository.... */
  String SAVEMODELTODB = "SAVEMODELTODB";
  /** Load model from repository.... */
  String LOADMODELFROMDB = "LOADMODELFROMDB";
  /** Load model.... */
  String LOADMODEL = "LOADMODEL";
  /** Exit. */
  String EXITPROGRAM = "EXITPROGRAM";
  /** Export. */
  String EXPORT = "EXPORT";
  /** as SVG. */
  String ASSVG = "ASSVG";
  /** as PNG. */
  String ASPNG = "ASPNG";
  /** as JPEG. */
  String ASJPEG = "ASJPEG";
  /** as BMP. */
  String ASBMP = "ASBMP";
  /** Database. */
  String DATABASE = "DATABASE";
  /** Classpath.... */
  String CLASSPATH = "CLASSPATH";
  /** DB - Connection.... */
  String DBCONNECTION = "DBCONNECTION";
  /** Repository connection.... */
  String REPOSITORYCONNECTION = "REPOSITORYCONNECTION";
  /** Last DB - Connections. */
  String STOREDDBCONNECTION = "STOREDDBCONNECTION";
  /** Reverse engineer.... */
  String REVERSEENGINEER = "REVERSEENGINEER";
  /** Domains.... */
  String DOMAINS = "DOMAINS";
  /** Default values.... */
  String DEFAULTVALUES = "DEFAULTVALUES";
  /** View. */
  String VIEW = "VIEW";
  /** Zoom in. */
  String ZOOMIN = "ZOOMIN";
  /** Zoom out. */
  String ZOOMOUT = "ZOOMOUT";
  /** . */
  String HAND = "HAND";
  /** . */
  String ENTITY = "ENTITY";
  /** . */
  String RELATION = "RELATION";
  /** . */
  String VIEWTOOL = "VIEWTOOL";
  /** Zoom. */
  String ZOOM = "ZOOM";
  /** Driver classpath configuration. */
  String CLASSPATHCONFIGURATION = "CLASSPATHCONFIGURATION";
  /** Database connection configuration. */
  String CONNECTIONCONFIGURATION = "CONNECTIONCONFIGURATION";
  /** Edit entity. */
  String ENTITYEDITOR = "ENTITYEDITOR";
  /** Edit relation. */
  String RELATIONEDITOR = "RELATIONEDITOR";
  /** Layout. */
  String LAYOUT = "LAYOUT";
  /** Layout by Graphviz. */
  String LAYOUTBYGRAPHVIZ = "LAYOUTBYGRAPHVIZ";
  /** Layout by RadialLayout (Experimental). */
  String LAYOUTBYRADIAL = "LAYOUTBYRADIAL";
  /** Layout by SpringLayout (Experimental. */
  String LAYOUTBYSPRING = "LAYOUTBYSPRING";
  /** Layout by GridLayout (Experimental. */
  String LAYOUTBYGRID = "LAYOUTBYGRID";
  /** Layout by TreeLayout (Experimental. */
  String LAYOUTBYTREE = "LAYOUTBYTREE";
  /** Layout by FRLayout (Experimental. */
  String LAYOUTBYFR = "LAYOUTBYFR";
  /** Name. */
  String NAME = "NAME";
  /** Declaration. */
  String DECLRATATION = "DECLRATATION";
  /** Java type. */
  String JAVATYPE = "JAVATYPE";
  /** Sequenzed. */
  String SEQUENCED = "SEQUENCED";
  /** Domain properties. */
  String DOMAINPROPERTIES = "DOMAINPROPERTIES";
  /** The attribute is part of a foreign key relation. */
  String ATTRIBUTEISUSEDINFOREIGNKEYS = "ATTRIBUTEISUSEDINFOREIGNKEYS";
  /** Information. */
  String INFORMATION = "INFORMATION";
  /** Error. */
  String ERROR = "ERROR";
  /** Question. */
  String QUESTION = "QUESTION";
  /** Do you really want to delete this element?. */
  String DOYOUREALLYWANTTODELETE = "DOYOUREALLYWANTTODELETE";
  /** The connection seems to be ok. */
  String CONNECTIONSEEMSTOBEOK = "CONNECTIONSEEMSTOBEOK";
  /** New. */
  String NEW = "NEW";
  /** Delete. */
  String DELETE = "DELETE";
  /** Update. */
  String UPDATE = "UPDATE";
  /** Ok. */
  String OK = "OK";
  /** Cancel. */
  String CANCEL = "CANCEL";
  /** Test. */
  String TEST = "TEST";
  /** Dialect. */
  String DIALECT = "DIALECT";
  /** Driver. */
  String JDBCDRIVER = "JDBCDRIVER";
  /** JDBC-URL. */
  String JDBCURL = "JDBCURL";
  /** User. */
  String USER = "USER";
  /** Password. */
  String PASSWORD = "PASSWORD";
  /** Default value properties. */
  String DEFAULTVALUEPROPERTIES = "DEFAULTVALUEPROPERTIES";
  /** . */
  String ADDFOLDER = "ADDFOLDER";
  /** . */
  String REMOVEFOLDER = "REMOVEFOLDER";
  /** . */
  String UP = "UP";
  /** . */
  String DOWN = "DOWN";
  /** Name. */
  String ENTITYNAME = "ENTITYNAME";
  /** Default. */
  String DEFAULT = "DEFAULT";
  /** Is NULLABLE. */
  String NULLABLE = "NULLABLE";
  /** Is primary key. */
  String PRIMARYKEY = "PRIMARYKEY";
  /** General. */
  String GENERAL = "GENERAL";
  /** Options. */
  String OPTIONS = "OPTIONS";
  /** Comments. */
  String COMMENTS = "COMMENTS";
  /** Attributes. */
  String ATTRIBUTES = "ATTRIBUTES";
  /** Indexes. */
  String INDEXES = "INDEXES";
  /** Nothing. */
  String DATABASEDEFAULT = "DATABASEDEFAULT";
  /** CASCADE. */
  String CASCADE = "CASCADE";
  /** SET NULL. */
  String SETNULL = "SETNULL";
  /** Relation name. */
  String RELATIONNAME = "RELATIONNAME";
  /** All in one file.... */
  String ALLINONEFILE = "ALLINONEFILE";
  /** One file per table.... */
  String ONEFILEPERTABLE = "ONEFILEPERTABLE";
  /** The element is in use and cannot be deleted. */
  String ELEMENTINUSE = "ELEMENTINUSE";
  /** Logical view(domains). */
  String LOGICALVIEW = "LOGICALVIEW";
  /** Physical view(declarations). */
  String PHYSICALVIEW = "PHYSICALVIEW";
  /** Table generation. */
  String TABLEGENERATION = "TABLEGENERATION";
  /** Domain generation. */
  String DOMAINGENERATION = "DOMAINGENERATION";
  /** Default generation. */
  String DEFAULTVALUEENERATION = "DEFAULTVALUEENERATION";
  /** You have to select at least one schema. */
  String CHOOSEONESCHEMA = "CHOOSEONESCHEMA";
  /** Standard. */
  String STANDART = "STANDART";
  /** Reverse engineering of schema {0}. */
  String ENGINEERINGSCHEMA = "ENGINEERINGSCHEMA";
  /** Reverse engineering of table {0}. */
  String ENGINEERINGTABLE = "ENGINEERINGTABLE";
  /** Reverse engineering of index {0}. */
  String ENGINEERINGINDEX = "ENGINEERINGINDEX";
  /** Index {0} is ignored. */
  String SKIPINDEX = "SKIPINDEX";
  /** Reverse engineering of relations for table {0}. */
  String ENGINEERINGRELATION = "ENGINEERINGRELATION";
  /** Reverse engineering finished. */
  String ENGINEERINGFINISHED = "ENGINEERINGFINISHED";
  /** Relation properties. */
  String RELATIONPROPERTIES = "RELATIONPROPERTIES";
  /** Attribute mapping. */
  String ATTRIBUTEMAPPING = "ATTRIBUTEMAPPING";
  /** Handling of ON DELETE. */
  String ONDELETEHANDLING = "ONDELETEHANDLING";
  /** Handling of ON UPDATE. */
  String ONUPDATEHANDLING = "ONUPDATEHANDLING";
  /** Schema options. */
  String SCHEMAOPTIONS = "SCHEMAOPTIONS";
  /** Engineering options. */
  String ENGINEERINGOPTIONS = "ENGINEERINGOPTIONS";
  /** Index is unique. */
  String INDEXISUNIQUE = "INDEXISUNIQUE";
  /** Index is not unique. */
  String INDEXISNOTUNIQUE = "INDEXISNOTUNIQUE";
  /** Index is primary key. */
  String INDEXISPRIMARY = "INDEXISPRIMARY";
  /** There is already a primary key. */
  String THEREISALREADYAPRIMARYKEY = "THEREISALREADYAPRIMARYKEY";
  /** Preferences.... */
  String PREFERENCES = "PREFERENCES";
  /** Path to DOT. */
  String DOTPATH = "DOTPATH";
  /** Error loading file. */
  String ERRORLOADINGFILE = "ERRORLOADINGFILE";
  /** File loaded. */
  String FILELOADED = "FILELOADED";
  /** File saved. */
  String FILESAVED = "FILESAVED";
  /** New model created. */
  String NEWMODELCREATED = "NEWMODELCREATED";
  /** Please define a database connection prior to using this operation!. */
  String PLEASEDEFINEADATABASECONNECTIONFIRST = "PLEASEDEFINEADATABASECONNECTIONFIRST";
  /** Size. */
  String SIZE = "SIZE";
  /** Fraction. */
  String FRACTION = "FRACTION";
  /** Scale. */
  String SCALE = "SCALE";
  /** Datatype. */
  String DATATYPE = "DATATYPE";
  /** An Index must contain at least one attribute!. */
  String INDEXMUSTHAVEATLEASTONEATTRIBUTE = "INDEXMUSTHAVEATLEASTONEATTRIBUTE";
  /** Create DDL for model.... */
  String GENERATECREATEDBDDL = "GENERATECREATEDBDDL";
  /** Execute. */
  String EXECUTESCRIPT = "EXECUTESCRIPT";
  /** Save to file. */
  String SAVESCRIPTTOFILE = "SAVESCRIPTTOFILE";
  /** SQL Window. */
  String SQLWINDOW = "SQLWINDOW";
  /** Exception ( Stacktrace ). */
  String EXCEPTIONWINDOW = "EXCEPTIONWINDOW";
  /** Close. */
  String CLOSE = "CLOSE";
  /** Current database changes.... */
  String GENERATECHANGELOG = "GENERATECHANGELOG";
  /** A table must have contain least one attribute!. */
  String TABLEMUSTHAVEATLEASTONEATTRIBUTE = "TABLEMUSTHAVEATLEASTONEATTRIBUTE";
  /** The database dialect is not supported!. */
  String DIALECTISNOTSUPPORTED = "DIALECTISNOTSUPPORTED";
  /** Extra. */
  String EXTRA = "EXTRA";
  /** Compare with database.... */
  String COMPLETECOMPARE = "COMPLETECOMPARE";
  /** Model. */
  String MODEL = "MODEL";
  /** Entity {0} is missing. */
  String MISSINGENTITY = "MISSINGENTITY";
  /** Attribute {0} is missing. */
  String MISSINGATTRIBUTE = "MISSINGATTRIBUTE";
  /** Redefined {0}. */
  String REDEFINED = "REDEFINED";
  /** Index {0} is missing. */
  String MISSINGINDEX = "MISSINGINDEX";
  /** Relation {0} is missing. */
  String MISSINGRELATION = "MISSINGRELATION";
  /** Layout finished. */
  String LAYOUTFINISHED = "LAYOUTFINISHED";
  /** Please enter the layout size in pixels. */
  String INPUTLAYOUTSIZE = "INPUTLAYOUTSIZE";
  /** The specified size is invalid. */
  String INVALIDSIZESPECIFIED = "INVALIDSIZESPECIFIED";
  /** Relations ( Foreign keys ). */
  String RELATIONS = "RELATIONS";
  /** Table selection. */
  String TABLESELECTION = "TABLESELECTION";
  /** Add to new subject area. */
  String ADDTONEWSUBJECTAREA = "ADDTONEWSUBJECTAREA";
  /** Subject area properties. */
  String SUBJECTAREAPROPERTIES = "SUBJECTAREAPROPERTIES";
  /** Edit subject area. */
  String SUBJECTAREAEDITOR = "SUBJECTAREAEDITOR";
  /** Color. */
  String COLOR = "COLOR";
  /** Models with subject areas are not supported by this operation. */
  String MODELSWITHSUBJECTAREASARENOTSUPPORTED = "MODELSWITHSUBJECTAREASARENOTSUPPORTED";
  /** Display element comments. */
  String DISPLAYCOMMENTS = "DISPLAYCOMMENTS";
  /** Display grid. */
  String DISPLAYGRID = "DISPLAYGRID";
  /** Editor grid size (px). */
  String EDITORGRIDSIZE = "EDITORGRIDSIZE";
  /** Edit comment. */
  String COMMENTEDITOR = "COMMENTEDITOR";
  /** Comment properties. */
  String COMMENTPROPERTIES = "COMMENTPROPERTIES";
  /** Domain editor.... */
  String DOMAINEDITOR = "DOMAINEDITOR";
  /** . */
  String COMMENT = "COMMENT";
  /** The exporting table needs to have a primary key. */
  String EXPORTINGTABLENEEDSPRIMARYKEY = "EXPORTINGTABLENEEDSPRIMARYKEY";
  /** Cannot delete element from model : {0}. */
  String CANNOTDELETEMODELITEM = "CANNOTDELETEMODELITEM";
  /** Display level. */
  String DISPLAYLEVEL = "DISPLAYLEVEL";
  /** All. */
  String DISPLAYALL = "DISPLAYALL";
  /** Primary keys only. */
  String DISPLAYPRIMARYKEY = "DISPLAYPRIMARYKEY";
  /** Primary and foreign keys. */
  String DISPLAYPRIMARYKEYANDFOREIGNKEY = "DISPLAYPRIMARYKEYANDFOREIGNKEY";
  /** Natural order. */
  String DISPLAYNATURALORDER = "DISPLAYNATURALORDER";
  /** Ascending order. */
  String DISPLAYASCENDING = "DISPLAYASCENDING";
  /** Descending order. */
  String DISPLAYDESCENDING = "DISPLAYDESCENDING";
  /** Attribute order. */
  String DISPLAYORDER = "DISPLAYORDER";
  /** Alias. */
  String ALIAS = "ALIAS";
  /** Create new entry. */
  String CREATENEWENTRY = "CREATENEWENTRY";
  /** Overwrite existing entry. */
  String OVERWRITEEXISTINGENTRY = "OVERWRITEEXISTINGENTRY";
  /** Delete entry. */
  String DELETEENTRY = "DELETEENTRY";
  /** New name. */
  String NEWNAME = "NEWNAME";
  /** An exception occoured while connecting to the repository. */
  String ERRORINREPOSITORYCONNECTION = "ERRORINREPOSITORYCONNECTION";
  /** Repository utilities.... */
  String REPOSITORYUTILS = "REPOSITORYUTILS";
  /** Create migration script.... */
  String CREATEMIGRATIONSCRIPT = "CREATEMIGRATIONSCRIPT";
  /** From version. */
  String FROMVERSION = "FROMVERSION";
  /** To version. */
  String TOVERSION = "TOVERSION";
  /** Attribute. */
  String ATTRIBUTE = "ATTRIBUTE";
  /** Expression. */
  String EXPRESSION = "EXPRESSION";
  /** . */
  String NEWONLYICON = "NEWONLYICON";
  /** This attribute is already part of this index. */
  String ATTRIBUTEALREADYPARTOFINDEX = "ATTRIBUTEALREADYPARTOFINDEX";
  /** . */
  String DELETEONLYICON = "DELETEONLYICON";
  /** This attribute is part of an index. */
  String ATTRIBUTEISUSEDININDEX = "ATTRIBUTEISUSEDININDEX";
  /** An index must include at least one expression or attribute!. */
  String ANINDEXMUSTHAVEATLEASTONEELEMENT = "ANINDEXMUSTHAVEATLEASTONEELEMENT";
  /** Edit view. */
  String VIEWEDITOR = "VIEWEDITOR";
}
