package de.erdesignerng;

/**
 * Automatically generated by XMLResourceBundleTask. DO NOT ALTER !
 */
public interface ERDesignerBundle {

  String BUNDLE_NAME = "de/erdesignerng/ERDesignerBundle";

  /** . */
  String TITLE = "TITLE";
  /** Datei. */
  String FILE = "FILE";
  /** Zuletzt benutzte Dateien. */
  String RECENTLYUSEDFILES = "RECENTLYUSEDFILES";
  /** Neues Modell. */
  String NEWMODEL = "NEWMODEL";
  /** Modell speichern.... */
  String SAVEMODEL = "SAVEMODEL";
  /** Modell laden.... */
  String LOADMODEL = "LOADMODEL";
  /** Programm beenden. */
  String EXITPROGRAM = "EXITPROGRAM";
  /** Export. */
  String EXPORT = "EXPORT";
  /** als SVG. */
  String ASSVG = "ASSVG";
  /** als PNG. */
  String ASPNG = "ASPNG";
  /** als JPEG. */
  String ASJPEG = "ASJPEG";
  /** als BMP. */
  String ASBMP = "ASBMP";
  /** Datenbank. */
  String DATABASE = "DATABASE";
  /** Klassenpfad.... */
  String CLASSPATH = "CLASSPATH";
  /** Datenbankverbindung.... */
  String DBCONNECTION = "DBCONNECTION";
  /** Reverse engineer.... */
  String REVERSEENGINEER = "REVERSEENGINEER";
  /** Domänen.... */
  String DOMAINS = "DOMAINS";
  /** Defaultwerte.... */
  String DEFAULTVALUES = "DEFAULTVALUES";
  /** Ansicht. */
  String VIEW = "VIEW";
  /** Vergrössern. */
  String ZOOMIN = "ZOOMIN";
  /** Verkleinern. */
  String ZOOMOUT = "ZOOMOUT";
  /** . */
  String HAND = "HAND";
  /** . */
  String ENTITY = "ENTITY";
  /** . */
  String RELATION = "RELATION";
  /** Vergrösserung. */
  String ZOOM = "ZOOM";
  /** Konfiguration Treiber-Klassenpfad. */
  String CLASSPATHCONFIGURATION = "CLASSPATHCONFIGURATION";
  /** Konfiguration Datenbankverbindung. */
  String CONNECTIONCONFIGURATION = "CONNECTIONCONFIGURATION";
  /** Entität editieren. */
  String ENTITYEDITOR = "ENTITYEDITOR";
  /** Relation editieren. */
  String RELATIONEDITOR = "RELATIONEDITOR";
  /** Layout. */
  String LAYOUT = "LAYOUT";
  /** Layout durch GraphViz. */
  String LAYOUTBYGRAPHVIZ = "LAYOUTBYGRAPHVIZ";
  /** Name. */
  String NAME = "NAME";
  /** Deklaration. */
  String DECLRATATION = "DECLRATATION";
  /** Java Typ. */
  String JAVATYPE = "JAVATYPE";
  /** Sequenziert. */
  String SEQUENCED = "SEQUENCED";
  /** Eigenschaften der Domäne. */
  String DOMAINPROPERTIES = "DOMAINPROPERTIES";
  /** Das Attribut ist Teil eines Fremdschlüssels. */
  String ATTRIBUTEISUSEDINFOREIGNKEYS = "ATTRIBUTEISUSEDINFOREIGNKEYS";
  /** Information. */
  String INFORMATION = "INFORMATION";
  /** Fehler. */
  String ERROR = "ERROR";
  /** Frage. */
  String QUESTION = "QUESTION";
  /** Wollen Sie das Element wirklich löschen?. */
  String DOYOUREALLYWANTTODELETE = "DOYOUREALLYWANTTODELETE";
  /** Die Verbindung scheint zu funktionieren. */
  String CONNECTIONSEEMSTOBEOK = "CONNECTIONSEEMSTOBEOK";
  /** Neu. */
  String NEW = "NEW";
  /** Löschen. */
  String DELETE = "DELETE";
  /** Aktualisieren. */
  String UPDATE = "UPDATE";
  /** Ok. */
  String OK = "OK";
  /** Abbrechen. */
  String CANCEL = "CANCEL";
  /** Test. */
  String TEST = "TEST";
  /** Dialekt. */
  String DIALECT = "DIALECT";
  /** Treiber. */
  String JDBCDRIVER = "JDBCDRIVER";
  /** JDBC-URL. */
  String JDBCURL = "JDBCURL";
  /** Benutzer. */
  String USER = "USER";
  /** Kennwort. */
  String PASSWORD = "PASSWORD";
  /** Eigenschaften des Defaultwertes. */
  String DEFAULTVALUEPROPERTIES = "DEFAULTVALUEPROPERTIES";
  /** . */
  String ADDFOLDER = "ADDFOLDER";
  /** . */
  String REMOVEFOLDER = "REMOVEFOLDER";
  /** . */
  String UP = "UP";
  /** . */
  String DOWN = "DOWN";
  /** Name der Entität. */
  String ENTITYNAME = "ENTITYNAME";
  /** Default. */
  String DEFAULT = "DEFAULT";
  /** Ist NULLABLE. */
  String NULLABLE = "NULLABLE";
  /** Ist Primärschlüssel. */
  String PRIMARYKEY = "PRIMARYKEY";
  /** Allgemeines. */
  String GENERAL = "GENERAL";
  /** Optionen. */
  String OPTIONS = "OPTIONS";
  /** Kommentare. */
  String COMMENTS = "COMMENTS";
  /** Attribute. */
  String ATTRIBUTES = "ATTRIBUTES";
  /** Indizes. */
  String INDEXES = "INDEXES";
  /** Nichts. */
  String DATABASEDEFAULT = "DATABASEDEFAULT";
  /** CASCADE. */
  String CASCADE = "CASCADE";
  /** SET NULL. */
  String SETNULL = "SETNULL";
  /** Name der Relation. */
  String RELATIONNAME = "RELATIONNAME";
  /** Alles in eine Datei.... */
  String ALLINONEFILE = "ALLINONEFILE";
  /** Eine Datei pro Tabelle.... */
  String ONEFILEPERTABLE = "ONEFILEPERTABLE";
  /** Das Element wird benutzt und kann daher nicht gelöscht werden. */
  String ELEMENTINUSE = "ELEMENTINUSE";
  /** Logische Ansicht(Domänen). */
  String LOGICALVIEW = "LOGICALVIEW";
  /** Physische Ansicht(Deklarationen). */
  String PHYSICALVIEW = "PHYSICALVIEW";
  /** Tablengenerierung. */
  String TABLEGENERATION = "TABLEGENERATION";
  /** Domänengenerierung. */
  String DOMAINGENERATION = "DOMAINGENERATION";
  /** Defaultgenerierung. */
  String DEFAULTVALUEENERATION = "DEFAULTVALUEENERATION";
  /** Sie müssen mindestens ein Schema auswählen. */
  String CHOOSEONESCHEMA = "CHOOSEONESCHEMA";
  /** Standard. */
  String STANDART = "STANDART";
  /** Reverseengineering von Schema {0}. */
  String ENGINEERINGSCHEMA = "ENGINEERINGSCHEMA";
  /** Reverseengineering von Tabelle {0}. */
  String ENGINEERINGTABLE = "ENGINEERINGTABLE";
  /** Reverseengineering von Relationen für Tabelle {0}. */
  String ENGINEERINGRELATION = "ENGINEERINGRELATION";
  /** Reverseengineering beendet. */
  String ENGINEERINGFINISHED = "ENGINEERINGFINISHED";
  /** Eigenschaften der Relation. */
  String RELATIONPROPERTIES = "RELATIONPROPERTIES";
  /** Mapping der Eigenschaften. */
  String ATTRIBUTEMAPPING = "ATTRIBUTEMAPPING";
  /** Behandlung von ON DELETE. */
  String ONDELETEHANDLING = "ONDELETEHANDLING";
  /** Behandlung von ON UPDATE. */
  String ONUPDATEHANDLING = "ONUPDATEHANDLING";
  /** Schema Optionen. */
  String SCHEMAOPTIONS = "SCHEMAOPTIONS";
  /** Engineering Optionen. */
  String ENGINEERINGOPTIONS = "ENGINEERINGOPTIONS";
  /** Index ist eindeutig. */
  String INDEXISUNIQUE = "INDEXISUNIQUE";
  /** Index ist nicht eindeutig. */
  String INDEXISNOTUNIQUE = "INDEXISNOTUNIQUE";
  /** Index ist Primärschlüssel. */
  String INDEXISPRIMARY = "INDEXISPRIMARY";
  /** Es existiert schon ein Primärschlüssel!. */
  String THEREISALREADYAPRIMARYKEY = "THEREISALREADYAPRIMARYKEY";
  /** Voreinstellungen.... */
  String PREFERENCES = "PREFERENCES";
  /** Pfad zu DOT. */
  String DOTPATH = "DOTPATH";
  /** Fehler beim Laden der Datei. */
  String ERRORLOADINGFILE = "ERRORLOADINGFILE";
  /** Datei erfolgreich geladen. */
  String FILELOADED = "FILELOADED";
  /** Datei erfolgreich gespeichert. */
  String FILESAVED = "FILESAVED";
  /** Neues Modell erzeugt. */
  String NEWMODELCREATED = "NEWMODELCREATED";
  /** Bitte definieren Sie vorher eine Datenbankverbindung!. */
  String PLEASEDEFINEADATABASECONNECTIONFIRST = "PLEASEDEFINEADATABASECONNECTIONFIRST";
  /** Grösse. */
  String SIZE = "SIZE";
  /** Nachkommastellen. */
  String FRACTION = "FRACTION";
  /** Skalierung. */
  String SCALE = "SCALE";
  /** Datentyp. */
  String DATATYPE = "DATATYPE";
  /** Ein Index muss mindestens ein Attribut beinhalten!. */
  String INDEXMUSTHAVEATLEASTONEATTRIBUTE = "INDEXMUSTHAVEATLEASTONEATTRIBUTE";
  /** DDL Generierung.... */
  String GENERATECREATEDBDDL = "GENERATECREATEDBDDL";
  /** Ausführen. */
  String EXECUTESCRIPT = "EXECUTESCRIPT";
  /** In Datei speichern. */
  String SAVESCRIPTTOFILE = "SAVESCRIPTTOFILE";
  /** SQL Fenster. */
  String SQLWINDOW = "SQLWINDOW";
  /** Fehler ( Stacktrace ). */
  String EXCEPTIONWINDOW = "EXCEPTIONWINDOW";
  /** Schliessen. */
  String CLOSE = "CLOSE";
  /** Aktuelle DB Änderungen.... */
  String GENERATECHANGELOG = "GENERATECHANGELOG";
  /** Eine Tabelle muss mindestens ein Attribut heinhalten. */
  String TABLEMUSTHAVEATLEASTONEATTRIBUTE = "TABLEMUSTHAVEATLEASTONEATTRIBUTE";
  /** Der Datenbankdialekt wird nicht unterstützt!. */
  String DIALECTISNOTSUPPORTED = "DIALECTISNOTSUPPORTED";
}
