ALTER TABLE TESTTABLE DROP CONSTRAINT TESTTABLE_PK;
CREATE PRIMARY KEY ON TESTTABLE(PK1,PK2);
DROP INDEX TESTTABLE_IDX1;
CREATE INDEX TESTINDEX ON TESTTABLE (AT2);
DROP INDEX TESTTABLE_IDX2;
CREATE UNIQUE INDEX TESTINDEX2 ON TESTTABLE (AT3);