package de.mogwai.erdesignerng;

/**
 * Automatically generated by XMLResourceBundleTask. DO NOT ALTER !
 */
public interface ERDesignerBundle {

  String BUNDLE_NAME = "de/mogwai/erdesignerng/ERDesignerBundle";

  /**  */
  String TITLE = "TITLE";
  /** Datei */
  String FILE = "FILE";
  /** Zuletzt benutzte Dateien */
  String RECENTLYUSEDFILES = "RECENTLYUSEDFILES";
  /** Neues Modell */
  String NEWMODEL = "NEWMODEL";
  /** Modell speichern */
  String SAVEMODEL = "SAVEMODEL";
  /** Modell laden */
  String LOADMODEL = "LOADMODEL";
  /** Programm beenden */
  String EXITPROGRAM = "EXITPROGRAM";
  /** Export */
  String EXPORT = "EXPORT";
  /** als SVG */
  String ASSVG = "ASSVG";
  /** als PNG */
  String ASPNG = "ASPNG";
  /** als JPEG */
  String ASJPEG = "ASJPEG";
  /** als BMP */
  String ASBMP = "ASBMP";
  /** Datenbank */
  String DATABASE = "DATABASE";
  /** Klassenpfad */
  String CLASSPATH = "CLASSPATH";
  /** Datenbankverbindung */
  String DBCONNECTION = "DBCONNECTION";
  /** Reverse engineer */
  String REVERSEENGINEER = "REVERSEENGINEER";
  /** Domänen */
  String DOMAINS = "DOMAINS";
  /** Defaultwerte */
  String DEFAULTVALUES = "DEFAULTVALUES";
  /** Ansicht */
  String VIEW = "VIEW";
  /** Vergrössern */
  String ZOOMIN = "ZOOMIN";
  /** Verkleinern */
  String ZOOMOUT = "ZOOMOUT";
  /**  */
  String HAND = "HAND";
  /**  */
  String ENTITY = "ENTITY";
  /**  */
  String RELATION = "RELATION";
  /** Vergrösserung */
  String ZOOM = "ZOOM";
  /** Konfiguration Treiber-Klassenpfad */
  String CLASSPATHCONFIGURATION = "CLASSPATHCONFIGURATION";
  /** Konfiguration Datenbankverbindung */
  String CONNECTIONCONFIGURATION = "CONNECTIONCONFIGURATION";
  /** Entität editieren */
  String ENTITYEDITOR = "ENTITYEDITOR";
  /** Relation editieren */
  String RELATIONEDITOR = "RELATIONEDITOR";
  /** Layout */
  String LAYOUT = "LAYOUT";
  /** Layout durch GraphViz */
  String LAYOUTBYGRAPHVIZ = "LAYOUTBYGRAPHVIZ";
}
