package de.erdesignerng;

/**
 * Automatically generated by XMLResourceBundleTask. DO NOT ALTER !
 */
public interface ERDesignerBundle {

  String BUNDLE_NAME = "de/erdesignerng/ERDesignerBundle";

  /**  */
  String TITLE = "TITLE";
  /** Datei */
  String FILE = "FILE";
  /** Zuletzt benutzte Dateien */
  String RECENTLYUSEDFILES = "RECENTLYUSEDFILES";
  /** Neues Modell */
  String NEWMODEL = "NEWMODEL";
  /** Modell speichern */
  String SAVEMODEL = "SAVEMODEL";
  /** Modell laden */
  String LOADMODEL = "LOADMODEL";
  /** Programm beenden */
  String EXITPROGRAM = "EXITPROGRAM";
  /** Export */
  String EXPORT = "EXPORT";
  /** als SVG */
  String ASSVG = "ASSVG";
  /** als PNG */
  String ASPNG = "ASPNG";
  /** als JPEG */
  String ASJPEG = "ASJPEG";
  /** als BMP */
  String ASBMP = "ASBMP";
  /** Datenbank */
  String DATABASE = "DATABASE";
  /** Klassenpfad... */
  String CLASSPATH = "CLASSPATH";
  /** Datenbankverbindung... */
  String DBCONNECTION = "DBCONNECTION";
  /** Reverse engineer... */
  String REVERSEENGINEER = "REVERSEENGINEER";
  /** Domänen... */
  String DOMAINS = "DOMAINS";
  /** Defaultwerte... */
  String DEFAULTVALUES = "DEFAULTVALUES";
  /** Ansicht */
  String VIEW = "VIEW";
  /** Vergrössern */
  String ZOOMIN = "ZOOMIN";
  /** Verkleinern */
  String ZOOMOUT = "ZOOMOUT";
  /**  */
  String HAND = "HAND";
  /**  */
  String ENTITY = "ENTITY";
  /**  */
  String RELATION = "RELATION";
  /** Vergrösserung */
  String ZOOM = "ZOOM";
  /** Konfiguration Treiber-Klassenpfad */
  String CLASSPATHCONFIGURATION = "CLASSPATHCONFIGURATION";
  /** Konfiguration Datenbankverbindung */
  String CONNECTIONCONFIGURATION = "CONNECTIONCONFIGURATION";
  /** Entität editieren */
  String ENTITYEDITOR = "ENTITYEDITOR";
  /** Relation editieren */
  String RELATIONEDITOR = "RELATIONEDITOR";
  /** Layout */
  String LAYOUT = "LAYOUT";
  /** Layout durch GraphViz */
  String LAYOUTBYGRAPHVIZ = "LAYOUTBYGRAPHVIZ";
  /** Name */
  String NAME = "NAME";
  /** Deklaration */
  String DECLRATATION = "DECLRATATION";
  /** Java Typ */
  String JAVATYPE = "JAVATYPE";
  /** Sequenziert */
  String SEQUENCED = "SEQUENCED";
  /** Eigenschaften der Domäne */
  String DOMAINPROPERTIES = "DOMAINPROPERTIES";
  /** Das Attribut ist Teil eines Fremdschlüssels */
  String ATTRIBUTEISUSEDINFOREIGNKEYS = "ATTRIBUTEISUSEDINFOREIGNKEYS";
  /** Information */
  String INFORMATION = "INFORMATION";
  /** Fehler */
  String ERROR = "ERROR";
  /** Frage */
  String QUESTION = "QUESTION";
  /** Wollen Sie das Element wirklich löschen? */
  String DOYOUREALLYWANTTODELETE = "DOYOUREALLYWANTTODELETE";
  /** Die Verbindung scheint zu funktionieren */
  String CONNECTIONSEEMSTOBEOK = "CONNECTIONSEEMSTOBEOK";
  /** Neu */
  String NEW = "NEW";
  /** Löschen */
  String DELETE = "DELETE";
  /** Aktualisieren */
  String UPDATE = "UPDATE";
  /** Ok */
  String OK = "OK";
  /** Abbrechen */
  String CANCEL = "CANCEL";
  /** Test */
  String TEST = "TEST";
  /** Dialekt */
  String DIALECT = "DIALECT";
  /** Treiber */
  String JDBCDRIVER = "JDBCDRIVER";
  /** JDBC-URL */
  String JDBCURL = "JDBCURL";
  /** Benutzer */
  String USER = "USER";
  /** Kennwort */
  String PASSWORD = "PASSWORD";
  /** Eigenschaften des Defaultwertes */
  String DEFAULTVALUEPROPERTIES = "DEFAULTVALUEPROPERTIES";
  /**  */
  String ADDFOLDER = "ADDFOLDER";
  /**  */
  String REMOVEFOLDER = "REMOVEFOLDER";
  /**  */
  String UP = "UP";
  /**  */
  String DOWN = "DOWN";
  /** Name der Entität */
  String ENTITYNAME = "ENTITYNAME";
  /** Default */
  String DEFAULT = "DEFAULT";
  /** Ist Pflichtfeld ( nicht NULL ) */
  String REQUIRED = "REQUIRED";
  /** Ist Primärschlüssel */
  String PRIMARYKEY = "PRIMARYKEY";
  /** Allgemeines */
  String GENERAL = "GENERAL";
  /** Optionen */
  String OPTIONS = "OPTIONS";
  /** Kommentare */
  String COMMENTS = "COMMENTS";
  /** Attribute */
  String ATTRIBUTES = "ATTRIBUTES";
  /** Indizes */
  String INDEXES = "INDEXES";
  /** Nichts */
  String DATABASEDEFAULT = "DATABASEDEFAULT";
  /** CASCADE */
  String CASCADE = "CASCADE";
  /** SET NULL */
  String SETNULL = "SETNULL";
  /** Name der Relation */
  String RELATIONNAME = "RELATIONNAME";
}
